logging:
  level:
    root: warn
spring:
  application:
    name: "kotlin-website"
  profiles:
    active: production
  main:
    banner-mode: off
    lazy-initialization: false
  data:
    mongodb:
      host: localhost
      database: kotlin-website
      port: 27017
      username: ${MONGO_INITDB_ROOT_USERNAME}
      password: ${MONGO_INITDB_ROOT_PASSWORD}
      authentication-database: admin
server:
  ssl:
    enabled: false
  servlet:
    context-path: /${spring.application.name}
  port: 8080
home:
  dj:
    username: ${USER_NAME}
    password: ${USER_PASSWORD}
    secret: ${PASSWORD_ENCODE_SECRET}
    iteration: ${PASSWORD_ENCODE_ITERATION}
    keyLength: ${PASSWORD_ENCODE_KEYLENGTH}
    admin: ${ADMIN_USER}
    adminPass: ${ADMIN_PASS}